import type { Metadata } from "next";
import { Inter } from "next/font/google";
import authBg from "@/public/images/auth-bg.png";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Authentication",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      className={`${inter.className} min-h-screen bg-cover bg-center bg-no-repeat antialiased text-white flex justify-center items-center`}
      style={{
        backgroundImage: `url(${authBg.src})`,
      }}
    >
      {children}
    </div>
  );
}
